import 'package:flutter/material.dart';

/// Mirrors IronClaw's ChannelType enum (src/channels/mod.rs).
enum IronClawChannelType {
  cli,
  slack,
  discord,
  telegram,
  whatsApp,
  matrix,
  irc,
  teams,
  webUi,
  restApi,
  webSocket,
  grpc,
  email,
  line,
  signal,
  blueBubbles,
  iMessage,
  zalo,
  zaloPersonal,
  googleChat;

  /// Exact variant name used in ironclaw.yaml channel config.
  String get configValue => switch (this) {
    cli          => 'Cli',
    slack        => 'Slack',
    discord      => 'Discord',
    telegram     => 'Telegram',
    whatsApp     => 'WhatsApp',
    matrix       => 'Matrix',
    irc          => 'Irc',
    teams        => 'Teams',
    webUi        => 'WebUi',
    restApi      => 'RestApi',
    webSocket    => 'WebSocket',
    grpc         => 'Grpc',
    email        => 'Email',
    line         => 'Line',
    signal       => 'Signal',
    blueBubbles  => 'BlueBubbles',
    iMessage     => 'IMessage',
    zalo         => 'Zalo',
    zaloPersonal => 'ZaloPersonal',
    googleChat   => 'GoogleChat',
  };
}

class IronClawChannel {
  final IronClawChannelType type;
  final String name;
  final String description;
  final IconData icon;
  final Color color;
  final String category; // 'local', 'messaging', 'api', 'enterprise', 'apple'
  final int rateLimitBurst;
  final int rateLimitSteady; // msgs/min
  final bool needsCredentials;
  final List<String> credentialKeys; // env var names or yaml keys needed

  const IronClawChannel({
    required this.type,
    required this.name,
    required this.description,
    required this.icon,
    required this.color,
    required this.category,
    required this.rateLimitBurst,
    required this.rateLimitSteady,
    required this.needsCredentials,
    this.credentialKeys = const [],
  });

  static const all = [
    IronClawChannel(
      type: IronClawChannelType.cli,
      name: 'CLI',
      description: 'Local command-line interface — always available',
      icon: Icons.terminal,
      color: Color(0xFF22C55E),
      category: 'local',
      rateLimitBurst: 100,
      rateLimitSteady: 60,
      needsCredentials: false,
    ),
    IronClawChannel(
      type: IronClawChannelType.webUi,
      name: 'Web UI',
      description: 'Browser dashboard with HMAC-SHA256 session auth',
      icon: Icons.dashboard,
      color: Color(0xFF6366F1),
      category: 'local',
      rateLimitBurst: 50,
      rateLimitSteady: 30,
      needsCredentials: false,
    ),
    IronClawChannel(
      type: IronClawChannelType.restApi,
      name: 'REST API',
      description: 'HTTP/JSON API for programmatic access',
      icon: Icons.api,
      color: Color(0xFF0EA5E9),
      category: 'api',
      rateLimitBurst: 200,
      rateLimitSteady: 120,
      needsCredentials: false,
    ),
    IronClawChannel(
      type: IronClawChannelType.webSocket,
      name: 'WebSocket',
      description: 'Real-time bidirectional streaming',
      icon: Icons.swap_horiz,
      color: Color(0xFF8B5CF6),
      category: 'api',
      rateLimitBurst: 100,
      rateLimitSteady: 60,
      needsCredentials: false,
    ),
    IronClawChannel(
      type: IronClawChannelType.grpc,
      name: 'gRPC',
      description: 'High-performance RPC for service-to-service comms',
      icon: Icons.cable,
      color: Color(0xFF64748B),
      category: 'api',
      rateLimitBurst: 500,
      rateLimitSteady: 300,
      needsCredentials: false,
    ),
    IronClawChannel(
      type: IronClawChannelType.slack,
      name: 'Slack',
      description: 'Slack bot via Events API',
      icon: Icons.forum,
      color: Color(0xFF4A154B),
      category: 'messaging',
      rateLimitBurst: 20,
      rateLimitSteady: 10,
      needsCredentials: true,
      credentialKeys: ['SLACK_BOT_TOKEN', 'SLACK_SIGNING_SECRET'],
    ),
    IronClawChannel(
      type: IronClawChannelType.discord,
      name: 'Discord',
      description: 'Discord bot via Gateway API',
      icon: Icons.gamepad,
      color: Color(0xFF5865F2),
      category: 'messaging',
      rateLimitBurst: 30,
      rateLimitSteady: 15,
      needsCredentials: true,
      credentialKeys: ['DISCORD_BOT_TOKEN'],
    ),
    IronClawChannel(
      type: IronClawChannelType.telegram,
      name: 'Telegram',
      description: 'Telegram Bot API',
      icon: Icons.send,
      color: Color(0xFF2AABEE),
      category: 'messaging',
      rateLimitBurst: 30,
      rateLimitSteady: 20,
      needsCredentials: true,
      credentialKeys: ['TELEGRAM_BOT_TOKEN'],
    ),
    IronClawChannel(
      type: IronClawChannelType.whatsApp,
      name: 'WhatsApp',
      description: 'WhatsApp Business Cloud API',
      icon: Icons.chat_bubble,
      color: Color(0xFF25D366),
      category: 'messaging',
      rateLimitBurst: 25,
      rateLimitSteady: 12,
      needsCredentials: true,
      credentialKeys: ['WHATSAPP_TOKEN', 'WHATSAPP_PHONE_ID'],
    ),
    IronClawChannel(
      type: IronClawChannelType.matrix,
      name: 'Matrix',
      description: 'Decentralised Matrix protocol (Element)',
      icon: Icons.grid_on,
      color: Color(0xFF0DBD8B),
      category: 'messaging',
      rateLimitBurst: 20,
      rateLimitSteady: 10,
      needsCredentials: true,
      credentialKeys: ['MATRIX_HOMESERVER', 'MATRIX_ACCESS_TOKEN'],
    ),
    IronClawChannel(
      type: IronClawChannelType.irc,
      name: 'IRC',
      description: 'Classic IRC protocol support',
      icon: Icons.chat,
      color: Color(0xFF6B7280),
      category: 'messaging',
      rateLimitBurst: 10,
      rateLimitSteady: 5,
      needsCredentials: true,
      credentialKeys: ['IRC_SERVER', 'IRC_NICK'],
    ),
    IronClawChannel(
      type: IronClawChannelType.teams,
      name: 'Microsoft Teams',
      description: 'Teams bot via Bot Framework',
      icon: Icons.groups,
      color: Color(0xFF6264A7),
      category: 'enterprise',
      rateLimitBurst: 25,
      rateLimitSteady: 12,
      needsCredentials: true,
      credentialKeys: ['TEAMS_APP_ID', 'TEAMS_APP_PASSWORD'],
    ),
    IronClawChannel(
      type: IronClawChannelType.googleChat,
      name: 'Google Chat',
      description: 'Google Workspace Chat bot',
      icon: Icons.mark_chat_unread,
      color: Color(0xFF1A73E8),
      category: 'enterprise',
      rateLimitBurst: 20,
      rateLimitSteady: 10,
      needsCredentials: true,
      credentialKeys: ['GOOGLE_CHAT_WEBHOOK'],
    ),
    IronClawChannel(
      type: IronClawChannelType.email,
      name: 'Email',
      description: 'SMTP/IMAP email channel',
      icon: Icons.email,
      color: Color(0xFFEA4335),
      category: 'messaging',
      rateLimitBurst: 10,
      rateLimitSteady: 3,
      needsCredentials: true,
      credentialKeys: ['EMAIL_HOST', 'EMAIL_USER', 'EMAIL_PASSWORD'],
    ),
    IronClawChannel(
      type: IronClawChannelType.line,
      name: 'LINE',
      description: 'LINE Messaging API (Japan/Asia)',
      icon: Icons.message,
      color: Color(0xFF00B900),
      category: 'messaging',
      rateLimitBurst: 20,
      rateLimitSteady: 10,
      needsCredentials: true,
      credentialKeys: ['LINE_CHANNEL_SECRET', 'LINE_CHANNEL_TOKEN'],
    ),
    IronClawChannel(
      type: IronClawChannelType.signal,
      name: 'Signal',
      description: 'Signal private messenger via signal-cli',
      icon: Icons.lock,
      color: Color(0xFF3A76F0),
      category: 'messaging',
      rateLimitBurst: 15,
      rateLimitSteady: 8,
      needsCredentials: true,
      credentialKeys: ['SIGNAL_PHONE_NUMBER'],
    ),
    IronClawChannel(
      type: IronClawChannelType.blueBubbles,
      name: 'BlueBubbles',
      description: 'iMessage via BlueBubbles server',
      icon: Icons.bubble_chart,
      color: Color(0xFF34AADC),
      category: 'apple',
      rateLimitBurst: 15,
      rateLimitSteady: 8,
      needsCredentials: true,
      credentialKeys: ['BLUEBUBBLES_SERVER_URL', 'BLUEBUBBLES_PASSWORD'],
    ),
    IronClawChannel(
      type: IronClawChannelType.iMessage,
      name: 'iMessage',
      description: 'Native iMessage (macOS bridging required)',
      icon: Icons.sms,
      color: Color(0xFF34AADC),
      category: 'apple',
      rateLimitBurst: 15,
      rateLimitSteady: 8,
      needsCredentials: true,
      credentialKeys: ['IMESSAGE_BRIDGE_URL'],
    ),
    IronClawChannel(
      type: IronClawChannelType.zalo,
      name: 'Zalo',
      description: 'Zalo OA (Official Account) API',
      icon: Icons.chat_bubble_outline,
      color: Color(0xFF0068FF),
      category: 'messaging',
      rateLimitBurst: 20,
      rateLimitSteady: 10,
      needsCredentials: true,
      credentialKeys: ['ZALO_OA_TOKEN'],
    ),
    IronClawChannel(
      type: IronClawChannelType.zaloPersonal,
      name: 'Zalo Personal',
      description: 'Zalo personal account messaging',
      icon: Icons.person_pin,
      color: Color(0xFF0068FF),
      category: 'messaging',
      rateLimitBurst: 10,
      rateLimitSteady: 5,
      needsCredentials: true,
      credentialKeys: ['ZALO_PERSONAL_TOKEN'],
    ),
  ];

  static List<IronClawChannel> byCategory(String cat) =>
      all.where((c) => c.category == cat).toList();
}
